### ISSUE TITLE
Xero Projects - 401 post error

### ISSUE THREAD

**Issue by kunallibra** [XeroAPI/xero-php-oauth2-starter#22]
Hi, 

I am facing two major problems:-

Problem 1

I am trying to integrate the xero project with the app build in laravel on my localhost. I have defined my scopes in the authorised.php file but it keeps me giving this error all the time. I have spelled it correct 'projects' and still giving the error. The error is :-

_"[401] Client error: `POST https://api.xero.com/projects.xro/2.0/Projects` resulted in a `401 Unauthorized` response:{"Type":null,"Title":"Unauthorized","Status":401,"Detail":"AuthorizationUnsuccessful","Instance":"131d4a62-129d-4809-9cf (truncated...)"_

I tested on the xero site (API Explorer) and am able to create the project successfully (New Kitchen e.g.)

When i run this code it gives an error as mentioned above.

```
projectCreateOrUpdate = new \XeroAPI\XeroPHP\Models\Project\ProjectCreateOrUpdate;
                 $projectCreateOrUpdate->setName("New Kitchen")
                ->setDeadlineUtc(Carbon::now())
                ->setEstimateAmount(199.00);


                 try {
                       $result = $apiInstance->createProject($xeroTenantId,$projectCreateOrUpdate);
                       print_r($result);
                   } catch (Exception $e) {
                       echo 'Exception when calling projectApi->createProject: ', $e->getMessage(), PHP_EOL;
                   }
```

The above code was given in the xero site  - project. Not too sure why this is not working.

Problem 2

After every 30 mins or so, I get logout automatically by xero and my access_token, refresh_token and id_token gets expired if i am actively using the api on my app. I then have to go to xero and get the new tokens and copy paste in a json file i have created to grant me the access. once i put the new tokens in the json file, it works for next 30 mins, which is not a ideal thing.

Is it possible or if u can point to the right direction where i can understand the sample code and automatically updates the code when required. 

Thanks u in advance.

Kunal

**Comment by Sallyhornet** [comment]
problem 1: Please can you get in touch with api@xero.com providing your client ID, timestamp etc 

problem 2: you'll need to implement the web authorisation flow, this is shown in the starter app, to keep going after 30 minutes you'll need to perform a token refresh

**Comment by RettBehrens** [comment]
Problem 1: It sounds like while you've requested the necessary scopes it's possible the user going through the auth/consent flow might not have the necessary permissions in Xero. Please contact api@xero.com if you are unsure.

Problem 2: It sounds like you are not refreshing your token set.

Access tokens expire after 30 minutes. Your app can refresh an access token without user interaction by using a refresh token. You get a refresh token by requesting the [offline_access](https://developer.xero.com/documentation/guides/oauth2/scopes#offline-access) scope during the initial user authorization. Refresh tokens expire after 60 days.

To refresh your access token you need to POST to the token endpoint:

https://identity.xero.com/connect/token

The request will require an authorization header containing your app’s client_id and client_secret

Authorization: "Basic " + base64encode(client_id + ":" + client_secret)
The request body will need to contain the grant type and refresh token

grant_type=refresh_token
refresh_token=Your refresh token
POST https://identity.xero.com/connect/token
authorization: "Basic " + base64encode(client_id + ":" + client_secret)
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&refresh_token=xxxxxx

The response will contain a new access token and refresh token. You must save both tokens in order to maintain api access.

If, for whatever reason, your app doesn’t receive the response, or fails to save the new token, you can retry using your existing refresh token for a grace period of 30 minutes. After 30 minutes your previous refresh token will expire and the user will need to re-authorise your api application in order to generate a new refresh token.
